# Generated by Django 4.1.7 on 2023-03-11 15:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre', max_length=100)),
                ('apellido', models.CharField(help_text='Apellido', max_length=100)),
                ('titulo', models.CharField(help_text='Titulo de la obra', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción de la obre en 300 caracteres', max_length=300)),
                ('imagen', models.ImageField(null=True, upload_to='imagen')),
                ('precio', models.IntegerField(default=1)),
                ('vendida', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('subtitulo', models.CharField(max_length=50)),
                ('texto', models.TextField(max_length=2000)),
                ('autor', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_posts')),
                ('fecha', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='usuario_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre', max_length=100)),
                ('apellido', models.CharField(help_text='Apellido', max_length=100)),
                ('imagen', models.ImageField(null=True, upload_to='avatares')),
                ('link', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(max_length=150, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
